replicaCount: 1

image:
  repository: ghcr.io/akhilxrawat/distill-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: distill.localhost
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/websocket-services: gateway
  tls:
    - hosts:
        - distill.localhost
      secretName: distill-gateway-tls

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

env:
  INGESTION_HOST: ingestion.distill-dev.svc.cluster.local
  INGESTION_PORT: "50051"
  STORAGE_HOST: storage.distill-dev.svc.cluster.local
  STORAGE_PORT: "50053"
  JWT_SECRET: "distill-secret-change-me"
