apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: storage
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: metrics
      port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    app: storage
