replicaCount: 1

image:
  repository: ghcr.io/akhilxrawat/distill-storage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50053

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

env:
  MONGODB_URI: "mongodb://mongodb.distill-dev.svc.cluster.local:27017/distill"
