name: Build Storage Service

on:
    push:
        paths:
            - 'services/storage/**'
            - 'proto/**'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
         
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/Login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}   

            - name: Build and push Docker image
              uses: docker/build-push-action@v5 
              with:
                context: .
                file: services/storage/Dockerfile
                push: true
                tags: |
                    ghcr.io/AkhilxRawat/distill-processing:${{ github.sha }}
                    ghcr.io/AkhilxRawat/distill-processing:latest 